# travis is a service that watches for changes (eg on Github) and
# then runs code
sudo: required

# tell travis we ned docker running
services:
  - docker

# build the image using the docker file.
# we tag the image so that we can easily reference it
before_install:
  - docker build -t zwilderrr/docker-react -f Dockerfile.dev .

# all the commands to run
script:
  # tell npm run test to exit when finished instead of waiting
  # for user input. This allows travis to advance to the next
  # step, because all Tavis is waiting for is a non-zero exit code
  # (eg no failure) from the previous step to continue
  - docker run zwilderrr/docker-react -e CI=true npm run test

# config to deploy to elastic beanstalk
deploy:
  # travis is preconfiged to connect
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  # s3 bucket aws created to hold our code. Travis sends our code
  # here
  bucket_name: "elasticbeanstalk-us-east-1-057346568725"
  # until first deploy, this will likely not have been created.
  # Until then, use the name of the app
  bucket_path: "docker-react"
  on:
    branch: master
  # credentials created in AWS and stored securely on Travis by
  # the following variable names
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
